version: '3'
services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is in the same directory as this compose file
    image: huimeidvops/rms-docker-img:latest
    container_name: rms-docker-container
